title: Restart - Journey of Computer Science
description: Documenting my footprints in Natural Language Processing, Machine Learning, SDE, and other CS domains.
theme: minima

navigation:
  - title: "Home"
    url: /
  - title: "Blog"
    url: /blog/
  - title: "Notes"
    url: /notes/

collections:
  notes:
    output: true
